### ISSUE TITLE
这个思路挺清晰的，可以简单的实现版本号替换了！

### ISSUE THREAD

**Issue by tcdona** [zwlijun/se.build#1]
去掉了 .htaccess 的方式，改为了 sed 命令？
请问可以说一下原因吗，脱离服务端依赖，方便cdn部署？

**Comment by zwlijun** [comment]
这是一个方面 .htaccess 这个局限性比较大，不同的webserver不一样。
所以后来采用sed查找替换的方式来处理了。

**Comment by tcdona** [comment]
ok，多谢，知道啦~
